name: Snyk

on:
  push:
    branches: [ master ]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/scala@master
        with:
          command: monitor
          args: --project-name=blob2stream
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
